from __future__ import annotations

TEMPLATES: dict[str, list[str]] = {
    "trash_kda": [
        "{name}'s KDA is {kda}. step it up this is horrible.",
        "A {kda} KDA? u deadass getting rolled and still playing this game?",
        "{name} is bot fragging as the teams bitch lately, call daddy glenn to come save you.",
        "With a {kda} KDA, {name} might just be jacking off with a finger up their ass while bombing ranked games.",
        "{name} has a {kda} KDA. moving as a fuckin clip bot ass boy.",
        "{kda} KDA is crazy work. {name} out here feeding like the enemy team pays him.",
        "bro {name} really just accepted a {kda} KDA and still queues. no shame left.",
        "{name}'s KDA looking like a participation trophy. {kda} is embarrassing.",
        "bro really woke up, looked at his {kda} KDA, and said ‘yeah I’ll queue again’. pure mental illness.",
        "{name} with a {kda} KDA is the reason ranked feels like a charity event.",
        "a {kda} KDA is not a stat, it’s a cry for help. {name} is out here doing the most and still looking soft.",
    ],
    "trash_hs": [
        "{hs}% headshot rate. oh nah and ur trying too. its ur mouse bro trust.",
        "{hs}% HS%, {name} might just be nervous. pussy.",
        "{name} quick reminder that u aint shit. {hs}% headshot rate not doin u justice LOL.",
        "being breastfed with your dads penis explains how {name} out here at {hs}% headshot rate.",
        "{name} spends their time in ranked games aiming for dicks. head out the gutter mud.",
        "{hs}% HS is actually criminal. {name} shooting at the floor like it owes him money.",
        "{name} is a fucking disgrace to the game. {hs}% headshot rate is a joke.",
        "{name} got {hs}% HS and still thinks they're cracked. delusion is a hell of a drug.",
        "that {hs}% HS is so bad I’m convinced {name} is shooting with his non-dominant nut.",
        "that {hs}% HS is so tragic it’s giving no thoughts head empty. {name} is spraying for the culture.",
        "{hs}% headshot percentage. {name} couldn’t hit a stationary target if it was glowing and begging for it.",
    ],
    "trash_winrate": [
        "{name} wins {wr}% of their games. the other {loss_wr}% gotta be glitches or something right?",
        "a {wr}% win rate. {name} IS FUCKING WINTRADING EVERYONE.",
        "{name} has a {wr}% win rate. take a break or do something else, nobody gon queue with u muddy.",
        "at {wr}% wins, {name} is currently banned with queuing with anyone in the server.",
        "AINT NOBODY GON QUEUE WITH YOUR {wr}% WIN RATE HAVIN ASS LOLLLLLL",
        "bro is hardstuck with a {wr}% win rate and still acts like he's the main character.",
        "{name}'s winrate so low the system started recommending unrated.",
        "{name}’s {wr}% win rate is so tragic the system should just force him into iron for life.",
        "bro is {wr}% and still has the audacity to type in chat. delete the game and your ego.",
        "{name}’s {wr}% win rate is so catastrophic the matchmaker should just put them in a private lobby alone.",
    ],
    "trash_acs": [
        "an ACS of {acs}. {name} is useless wtf.",
        "{acs} average combat score. {name} aint combatting shiiiiii.",
        "{name} got {acs} ACS. wait ur actually a bum.",
        "with {acs} ACS, {name} might actually be successful as a cheerleader if they had tits.",
        "{acs} ACS. {name} we know you suck dick for elo its aii.",
        "{acs} ACS is crazy. {name} contributing less than the spike itself.",
        "that ACS looking like {name} is just there for moral support. {acs} is crazy work.",
        "that {acs} ACS is criminal. {name} is just there to make the enemy feel good about themselves.",
        "{acs} ACS is not low, it’s a statement. {name} came to lose on purpose.",
    ],
    "decent": [
        "{name} is a mid ass player wit sum mid ass stats.",
        "{name}'s stats are so mid i genuinely got nun to say. {kda} KDA, {wr}% wins. checks out.",
        "a {kda} KDA and {wr}% win rate. {name} a fuckin npc. son im crine.",
        "{name} consistently mid as fuck. do SOMETHING.",
        "aint shit tbh. {name} is still glenns bitch tho",
        "{name} is so mid the scoreboard doesn’t even acknowledge him. pure background character.",
        "stats so average I’m convinced {name} is an AI designed to fill lobbies.",
        "{name} neither hard carries nor hard throws. just existing in the void. impressive in a sad way.",
        "stats so average {name} might as well be a default skin bot. zero sauce, zero impact.",
    ],
    "good_performance": [
        "damn {name} actually said fuck it and started performing. {kda} kda, {acs} acs. still mid tho.",
        "{name} cooked lately ngl. {kda} kda and {hs}% hs. dont get too comfortable tho pussy.",
        "okay {name} we see u. {wr}% wins and {kda} kda lately. its giving less ass than usual.",
        "{name} is actually bussin rn and we hate it. {kda} kda, {acs} acs. somebody bench this bum before he gets confident.",
        "ngl {name} u been playing good and it makes me uncomfortable as hell. {kda} kda {wr}% wins. still our bitch tho.",
        "{name} finally woke up and decided to frag. temporary boost, we'll be roasting you again soon.",
        "rare {name} W streak. enjoy it while it lasts, the falloff is coming.",
        "rare {name} performance. enjoy the dopamine before you go back to being dogshit.",
        "{name} cooked this week and the whole server is unsettled. don’t get used to it pussy.",
        "okay {name} we see the {kda} KDA. still our bitch though, don’t forget your place.",
    ],
    "comparison_win": [
        "{name} won this comparison. not a glitch. clearly the fuckin goat",
        "{name} just absolutely molested {name2} in the stats. no recovery from that.",
        "stop dissing on {name}'s name and get a boost from them.",
        "{name} IS BETTER. might take yo bitch too.",
        "{name} get this bitch boosted and call this command again.",
        "{name} owns the fuck out of {name2} and must submit themselves at the feet of the goat. ",
        "take this shit as a lesson. dont ever try it again {name2}.",
        "{name} just bodybagged {name2} in the stats. embarrassing for the loser.",
        "clear gap. {name} is the father and {name2} is the disappointed son.",
        "{name} owns {name2} so hard the system should just auto-mute the loser.",
        "{name2} got diffed into oblivion. {name} is the superior specimen.",
    ],
    "comparison_loss": [
        "{name} LMFAOOO ur this guys bitch dont ever speak or call this command again.",
        "rough day for {name}. bodied and bitched dont ever try it again.",
        "{name} i labeled u as a bitch in the system. we aint forgetting this one.",
        "yikes. {name} ban this mf from the server.",
        "{name} thought he was shit and got bodied. i'm gonna tell everyone on the server.",
        "{name} just got cooked by {name2}. delete the game and touch grass.",
        "stats said {name} is inferior. no discussion needed. sit.",
        "rough. {name} is officially {name2}’s personal bitch now. no take-backs.",
        "stats said {name} is inferior and the whole lobby agreed. go next.",
    ],
}
